export enum ActionTypes {
  TODOS_LOAD = 'TODOS_LOAD',
  REMOVE_TODO = 'REMOVE_TODO',
  SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER',
  RANDOMIZE_TODOS = 'RANDOMIZE_TODOS',
  USER_LOAD = 'USER_LOAD',
  CLEAR_USER = 'CLEAR_USER',
  TOGGLE_COMPLETED = 'TOGGLE_COMPLETED',
}
