export enum ActionTypes {
  TODOS_LOAD = 'TODOS_LOAD',
  SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER',
  RANDOMIZE_TODOS = 'RANDOMIZE_TODOS',
  LOAD_USER = 'USER_LOAD',
  CLEAR_USER = 'CLEAR_USER',
  DELETE_TODO = 'REMOVE_TODO',
  TOGGLE_COMPLETED = 'TOGGLE_COMPLETED',
}

export enum FilterTypes {
  SHOW_ALL = 'SHOW_ALL',
  SHOW_COMPLETED = 'SHOW_COMPLETED',
  SHOW_ACTIVE = 'SHOW_ACTIVE',
}
