export enum ActionTypes {
  LOAD_TODOS = 'TODOS_LOAD',
  SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER',
  LOAD_USER = 'LOAD_USER',
  CLEAR_USER = 'CLEAR_USER',
  DELETE_TODO = 'DELETE_TODO',
  TOGGLE_COMPLETED = 'TOGGLE_COMPLETED',
}

export enum FilterTypes {
  SHOW_ALL = 'SHOW_ALL',
  SHOW_COMPLETED = 'SHOW_COMPLETED',
  SHOW_ACTIVE = 'SHOW_ACTIVE',
}
