const FETCH_TODOS_REQUEST = 'FETCH_TODOS_REQUEST';
const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
const TODOS_REQUEST_ERROR = 'TODOS_REQUEST_ERROR';
const USERS_REQUEST_ERROR = 'USERS_REQUEST_ERROR';
const TODO_COMPLETE = 'TODO_COMPLETE';
const TODO_SORT = 'TODO_SORT';
const TODO_DELETE = 'TODO_DELETE';


export {
  FETCH_TODOS_REQUEST,
  FETCH_USERS_REQUEST,
  FETCH_TODOS_SUCCESS,
  FETCH_USERS_SUCCESS,
  TODOS_REQUEST_ERROR,
  USERS_REQUEST_ERROR,
  TODO_COMPLETE,
  TODO_SORT,
  TODO_DELETE,
};
